foodles/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('recipe/', views.RecipeList.as_view(), name='recipes_index'),
    path('recipe/<int:pk>/', views.RecipeDetail.as_view(), name='recipes_detail'),
    path('recipe/create/', views.RecipeCreate.as_view(), name='recipes_create'),
    path('recipe/favorites/', views.FavoriteList.as_view(), name='view_favorites'),
    path('recipe/main/', views.MainList.as_view(), name='view_by_main'),
    path('recipe/main/sort', views.IngredientView, name='main_sort'),
    path('recipe/<int:pk>/update/', views.RecipeUpdate.as_view(), name='recipes_update'),
    path('recipe/<int:pk>/delete/', views.RecipeDelete.as_view(), name='recipes_delete'),
    path('recipe/<int:pk>/make_favorite', views.recipes_make_favorite, name='recipes_make_favorite'),
    path('recipe/<int:pk>/remove_favorite', views.recipes_remove_favorite, name='recipes_remove_favorite'),
    path('recipe/<int:recipe_id>/add_photo/', views.add_photo, name='add_photo'),
    path('accounts/signup/', views.signup, name='signup'),
    path('meals/', views.MealList.as_view(), name='meals_index'),
    path('meals/<int:pk>/', views.MealDetail.as_view(), name='meals_detail'),
    path('meal/create/', views.MealCreate.as_view(), name='meals_create'),
    path('meal/<int:pk>/update/', views.MealUpdate.as_view(), name='meals_update'),
    path('meal/<int:pk>/delete/', views.MealDelete.as_view(), name='meals_delete'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date

# Create your models here.

MEAL_TYPE = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner'),
)

MAIN_INGREDIENT = (
    ('C', 'Chicken'),
    ('P', 'Pork'),
    ('B', 'Beef'),
    ('F', 'Fish'),
    ('S', 'Shellfish'),
    ('L', 'Lamb'),
    ('N', 'Pasta'),
    ('V', 'Vegetarian'),
    ('O', 'Other'),
)

class Recipe(models.Model):
    name = models.CharField(max_length=100)
    source = models.CharField(max_length=100)
    instructions = models.TextField()
    favorite = models.BooleanField(default=False)
    main_ingredient = models.CharField(
        max_length=1,
        choices=MAIN_INGREDIENT,
        default=MAIN_INGREDIENT[0][0]
    )    
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('recipes_detail', kwargs={'pk': self.id})

class Meal(models.Model):
    date = models.DateField('meal date')
    recipe = models.ManyToManyField(Recipe)
    meal_type = models.CharField(
        max_length=1,
        choices=MEAL_TYPE,
        default=MEAL_TYPE[0][0]
    )

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('meals_detail', kwargs={'pk': self.id})

    def recipe_peek(self):
        return self.recipe.values('name', 'id')
    
class Photo(models.Model):
    url = models.CharField(max_length=200)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for recipe_id: {self.recipe_id} @{self.url}"

main_app/views.py
import uuid
import boto3
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Meal, Recipe, MAIN_INGREDIENT, Photo

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'foodles-1'


def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('about')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

class RecipeList(ListView):
  model = Recipe

class RecipeDetail(DetailView):
  model = Recipe

class RecipeCreate(LoginRequiredMixin, CreateView):
  model = Recipe
  fields = ['name', 'source', 'main_ingredient', 'instructions']
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class RecipeUpdate(LoginRequiredMixin, UpdateView):
  model = Recipe
  fields = ['name', 'source', 'main_ingredient', 'instructions']

class RecipeDelete(LoginRequiredMixin, DeleteView):
  model = Recipe
  success_url = '/recipe/'

class MealList(ListView):
  model = Meal

class MealDetail(DetailView):
  model = Meal

class MealCreate(LoginRequiredMixin, CreateView):
  model = Meal
  fields = ['date', 'recipe', 'meal_type']
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)
  success_url = '/meals/'

class MealUpdate(LoginRequiredMixin, UpdateView):
  model = Meal
  fields = ['date', 'recipe', 'meal_type']

class MealDelete(LoginRequiredMixin, DeleteView):
  model = Meal
  success_url = '/meals/'

def recipes_make_favorite(request, pk):
  current_recipe = Recipe.objects.get(id=pk)
  current_recipe.favorite = True
  current_recipe.save()
  return redirect('view_favorites')

def recipes_remove_favorite(request, pk):
  current_recipe = Recipe.objects.get(id=pk)
  current_recipe.favorite = False
  current_recipe.save()
  return redirect('/recipe/')

class FavoriteList(LoginRequiredMixin, ListView):
  context_object_name = 'favorites'
  queryset = Recipe.objects.filter(favorite=True)
  template_name = 'main_app/view_favorites.html'

class MainList(LoginRequiredMixin, ListView):
  queryset = Recipe.objects.all()
  template_name = 'main_app/view_by_main.html'

def IngredientView(request):
  ingredient = chr(request.body[-1])
  recipes = Recipe.objects.filter(main_ingredient=ingredient)
  print(ingredient)
  return render(request, 'main_app/main_sort.html', {'recipes':recipes})

def add_photo(request, recipe_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            Photo.objects.create(url=url, recipe_id=recipe_id)
        except:
            print('An error occurred uploading file to S3')
    return redirect('recipes_detail', pk=recipe_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>Foodles About Page</h1>
<br>
<p>This site was built by a group of like minded people putting their 
skills together to solve this dilemma of forgetting about great recipes</p>
<br>
<p>When was the last time you had that New York Times Fried Chicken 
dish? Is Grandma’s Cornbread really as good as you remember it being last 
Thanksgiving? Foodles is a meal app that will 
track your culinary masterpieces and let you know 
when it’s time to give that recipe another try.</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>f o o d l e s</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <script
      src="https://kit.fontawesome.com/8aea6a0231.js"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav class="navbar">
        <div class="nav-wrapper">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/"
                ><i class="fas fa-home"></i
                ><span class="link-text">Home</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}"
                ><i class="fas fa-info-circle"></i
                ><span class="link-text"> About</span></a
              >
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'recipes_index' %}"
                ><i class="fas fa-book"></i
                ><span class="link-text"> Recipes</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'recipes_create' %}"
                ><i class="fas fa-book-open"></i
                ><span class="link-text"> Add Recipe</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'meals_index' %}"
                ><i class="fab fa-delicious"></i
                ><span class="link-text"> Meals</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'meals_create' %}"
                ><i class="far fa-plus-square"></i
                ><span class="link-text"> Add Meal</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}"
                ><i class="fas fa-sign-out-alt"></i
                ><span class="link-text"> Log Out</span></a
              >
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}"
                ><i class="fas fa-user-plus"></i
                ><span class="link-text">Sign Up</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}"
                ><i class="fas fa-sign-in-alt"></i
                ><span class="link-text"> Log In</span></a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">Not your average recipe book &nbsp;</div>
      <br />
      <div class="right">
        All Rights Reserved, &copy; 2020 Foodles&trade; &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="center-align">
<h1>Welcome to Foodles</h1>
{% if user.is_authenticated %}
<h2>Take a look around</h2>
{% else %}
<h2>Please Log In!</h2>
<br><br>
<a href="{% url 'signup' %}" class="btn" class="home-btn">Sign Up</a>
<a href="{% url 'login' %}" class="btn" class="home-btn">Login In</a>
</div>
{% endif %}

{% endblock %}

main_app/templates/main_app/main_sort.html
{% extends 'base.html' %} {% block content %} {% if recipes.count %} {% for
recipe in recipes.all %}
<a href="{% url 'recipes_detail' recipe.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ recipe.name }}</span>
      <p>Source: {{ recipe.source|truncatechars:25 }}</p>
      <p>Main Ingredient: {{ recipe.get_main_ingredient_display }}</p>
      <p>Instructions: {{ recipe.instructions|truncatechars:50 }}</p>
      {% if recipe.favorite %}
      <p>Favorite</p>
      {% endif %}
    </div>
  </div>
</a>
{% endfor %} {% else %}
<h1>no recipes</h1>
{% endif %} {% endblock %}

main_app/templates/main_app/meal_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Meal</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.date }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'meals_detail' object.id  %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/meal_detail.html
{% extends 'base.html' %} {% block content %}

<h1>Meal Details</h1>
<div class="card">
  <div class="card-content">
    <span class="card-title"><h4>{{ meal.date }}</h4></span>
    <h4>{{ meal.get_meal_type_display }}</h4>
    <h6>Recipes:</h6>
    {% for recipe in meal.recipe_peek %}
    <ul>
      <li><a href="/recipe/{{ recipe.id }}">{{ recipe.name }}</a></li>
    </ul>

    {% endfor %}
  </div>
  <div class="card-action">
    <a class="btn-small" href="{% url 'meals_update' meal.id %}">Edit</a>
    <a class="btn-small" href="{% url 'meals_delete' meal.id %}">Delete</a>
    <br /><br />
  </div>

  {% endblock %}
</div>

main_app/templates/main_app/meal_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Meal</h1>
{% endif %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>

<script>
  var dateEl = document.getElementById("id_date");
  M.Datepicker.init(dateEl, {
    format: "yyyy-mm-dd",
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });
  var selectElement = document.getElementById("id_meal_type");
  M.FormSelect.init(selectElement);
  // initialize the meal select
  var selectEl = document.getElementById("id_recipe");
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/main_app/meal_list.html
{% extends 'base.html' %}

{% block content %}

<h1>My Recent Meals</h1>

{% for meal in meal_list %}
<a href="{% url 'meals_detail' meal.id %}">
<div class="card card-list">
  <div class="card-content">
      <span class="card-title">{{ meal.get_meal_type_display }} on {{meal.date}}</span>
      {% for recipe in meal.recipe_peek %}
      <section class="content">
        <p>{{ recipe.name }}</p>
      </section>
      {% endfor %}
  </div>
</div>
</a>
{% endfor %}
{% endblock %}

main_app/templates/main_app/recipe.html
{% extends 'base.html' %}
{% block content %}

<h1>Foodles Recipes</h1>

{% endblock %}

main_app/templates/main_app/recipe_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Recipe</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'recipes_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/recipe_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Recipe Details</h1>
<div class="card">
    <div class="card-content">
      <span class="card-title">{{ recipe.name }}</span>
      <p>Main Ingredient: {{ recipe.get_main_ingredient_display }}</p>                        
      <p>Source: {{ recipe.source }}</p>
      <p>Instructions: {{ recipe.instructions }}</p>
    </div>
<div class="card-action">
    <a class="btn-small" href="{% url 'recipes_update' recipe.id %}">Edit</a>
    <a class="btn-small delete" href="{% url 'recipes_delete' recipe.id %}">Delete</a>
    <br><br>
    {% if recipe.favorite == False %}
    <form action="{% url 'recipes_make_favorite' recipe.id %}" method="post">
      {% csrf_token %}
      <input type="submit" value="Add to Favorites!" class="btn">
    </form>
  </div>
  {% else %}
  <form action="{% url 'recipes_remove_favorite' recipe.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Remove Favorite" class="btn">
  </form>
</div>
{% endif %}
{% for photo in recipe.photo_set.all %}
  <img class="responsive-img card-panel" src="{{photo.url}}">
{% empty %}
  <div class="card-panel teal-text center-align">No Photos Uploaded</div>
{% endfor %}
  <form action="{% url 'add_photo' recipe.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
    {% csrf_token %}
    <input type="file" name="photo-file">
    <br><br>
    <input type="submit" class="btn" value="Upload Photo">
  </form>


{% endblock %}

main_app/templates/main_app/recipe_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Recipe</h1>
{% endif %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
<script>
  const selectEl = document.getElementById("id_main_ingredient");
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/main_app/recipe_list.html
{% extends 'base.html' %} {% block content %}

<h1>Recipe List</h1>
<div class="center-align" id="wrapper">
  <a class="btn-small" href="{% url 'view_favorites' %}">Favorite Recipes</a>
  <a class="btn-small" href="{% url 'view_by_main' %}"
    >Recipes By Main Ingredient</a
  >
</div>
{% for recipe in recipe_list %}
<a href="{% url 'recipes_detail' recipe.id %}">
  <div class="card card-list">
    <div class="card-content">
      <span class="card-title">{{ recipe.name }}</span>
      <p>Source: {{ recipe.source|truncatechars:25 }}</p>
      <p>Main Ingredient: {{ recipe.get_main_ingredient_display }}</p>
      <p>Instructions: {{ recipe.instructions|truncatechars:50 }}</p>
      {% if recipe.favorite %}
      <p>Favorite</p>
      {% endif %}
    </div>
  </div>
</a>
{% endfor %} {% endblock %}

main_app/templates/main_app/view_by_main.html
{% extends 'base.html' %}
{% block content %}
<h2>View Recipes By Main Ingredient</h2>
<form action='/recipe/main/sort' method="POST">
    {% csrf_token %}
    <div class="input-field col s12">
    <select name="main_ingredient">
        <option value="C">Chicken</option>
        <option value="P">Pork</option>
        <option value="B">Beef</option>
        <option value="F">Fish</option>
        <option value="S">Shellfish</option>
        <option value="L">Lamb</option>
        <option value="P">Pasta</option>
        <option value="V">Vegetarian</option>
        <option value="O">Other</option>
    </select>
    <label>Select Main Ingredient</label>
    </div>
    <input type="submit" />
  </form>


{% for recipe in recipes %}
  <a href="{% url 'recipes_detail' recipe.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ recipe.name }}</span>
            <p>Source: {{ recipe.source|truncatechars:25 }}</p>
            <p>Main Ingredient: {{ recipe.get_main_ingredient_display }}</p>
            <p>Instructions: {{ recipe.instructions|truncatechars:50 }}</p>
            {% if recipe.favorite %}
            <p>Favorite</p>
            {% endif %}

        </div>
    </div>
  </a>
{% endfor %}

<script>
    document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems);
  });
  </script>
{% endblock %}

main_app/templates/main_app/view_favorites.html
{% extends 'base.html' %}
{% block content %}
<h1>My Favorite Recipes</h1>
{% for recipe in favorites %}
  <a href="{% url 'recipes_detail' recipe.id %}">
    <div class="card card-list">
        <div class="card-content">
            <span class="card-title">{{ recipe.name }}</span>
            <p>Source: {{ recipe.source|truncatechars:25 }}</p>
            <p>Main Ingredient: {{ recipe.get_main_ingredient_display }}</p>
            <p>Instructions: {{ recipe.instructions|truncatechars:50 }}</p>
            {% if recipe.favorite %}
            <p>Favorite</p>
            {% endif %}

        </div>
    </div>
  </a>
{% endfor %}
{% endblock %}